{block #title}Knihovny{/block}
{block #chapter}F.{/block}
{block #content}

<h3>Seznam všech knihoven použitých v JCOPu</h3>

<p>
  V <a href="#table-1">tabulce 1</a> je seznam všech knihoven třetích stran používaných v JCOPu, společně s jejich
  krátkým popisem, domovskou stránkou a které části JCOPu ji využívají.
</p>

<table class="full" id="table-1">
  <tr>
    <th>Název</th>
    <th>Popis</th>
    <th>Homepage</th>
    <th>Použití</th>
  </tr>
  <tr>
    <td><a href="#ecs" class="nobr">Jakarta ECS</a></td>
    <td>ECS umožňuje používat javové objekty na generování (X)HTML/XML kódu.</td>
    <td><a href="http://jakarta.apache.org/ecs/" class="nobr">jakarta.apache.org/ecs/</a></td>
    <td>{javadoc "result.render.XMLRender"}</td>
  </tr>
  <tr>
    <td><a href="#java-csv" class="nobr">Java CSV</a></td>
    <td>Knihovna pro čtení a zápis do CSV souborů.</td>
    <td><a href="http://sourceforge.net/projects/javacsv/" class="nobr">sourceforge.net/projects/javacsv/</a></td>
    <td>{javadoc "result.render.CSVRender"}</td>
  </tr>
  <tr>
    <td><a href="#jfreechart">JFreeChart</a></td>
    <td>Zobrazuje různé typy grafů.</td>
    <td><a href="http://jfree.org/jfreechart/" class="nobr">jfree.org/jfreechart/</a></td>
    <td>{javadoc "result.render.JFreeChartRender"}</td>
  </tr>
  <tr>
    <td><a href="#jfreechart">Log4j</a></td>
    <td>Umožňuje nízkoúrovňové logování.</td>
    <td><a href="http://logging.apache.org/log4j/" class="nobr">logging.apache.org/log4j/</a></td>
    <td>mnoho míst v celém projektu</td>
  </tr>
</table>