{block #title}Stop Conditions (ukončovací podmínky){/block}
{block #chapter}D.{/block}
{block #content}

<h3>Seznam všech ukončovacích podmínek v&nbsp;JCOPu</h3>

<p>
  V <a href="#table-1">tabulce 1</a> je seznam všech ukončovacích podmínek dodávaných s&nbsp;JCOPem, společně s&nbsp;popisem kdy
  jsou splněny a&nbsp;jaké přijímají zprávy. Všechny zde uvedené podmínky dědí z {javadoc "solver.condition.BaseCondition"}.
</p>

<table class="full" id="table-1">
  <tr>
    <th>Jméno</th>
    <th>Splněna</th>
    <th>Přijímané zprávy</th>
  </tr>
  <tr>
    <td><a href="#and-condition">AndCondition</a></td>
    <td>všechny podmínky jsou splněny</td>
    <td>žádné</td>
  </tr>
  <tr>
    <td><a href="#found-solution-condition">FoundSolutionCondition</a></td>
    <td>{javadoc "solver.message.MessageSolutionFound"} přijata</td>
    <td>{javadoc "solver.message.MessageSolverStart"}<br/>{javadoc "solver.message.MessageSolutionFound"}</td>
  </tr>
  <tr>
    <td><a href="#iteration-condition">IterationCondition</a></td>
    <td>{javadoc "solver.message.MessageOptimize"} přijata daný počet kroků</td>
    <td>{javadoc "solver.message.MessageSolverStart"}<br/>{javadoc "solver.message.MessageOptimize"}</td>
  </tr>
  <tr>
    <td><a href="#or-condition">OrCondition</a></td>
    <td>libovolná dílčí podmínka je splněna</td>
    <td>žádné</td>
  </tr>
  <tr>
    <td><a href="#timeout-condition">TimeoutCondition</a></td>
    <td>CPU time solveru nabyl dostatečné hodnoty</td>
    <td>{javadoc "solver.message.MessageSolverStart"}</td>
  </tr>
</table>
<p class="fig-title">Table 1: Seznam všech ukončovacích podmínek v&nbsp;JCOPu.</p>

<h3 id="and-condition">AndCondition</h3>

<p>
  {javadoc "solver.condition.AndCondition"} se používá na vytváření komplexních podmínek. Může v&nbsp;sobě obsahovat
  libovolné množství dalších ukončovacích podmínek (dodané buď v&nbsp;konstruktoru nebo voláním {javadoc "solver.condition.AndCondition#addStopCondition(cz.cvut.felk.cig.jcop.solver.condition.StopCondition)"}).
  Kdykoli je podmínka vyhodnocena, vrací true, právě když žádná dílčí ukončovací podmínka nevrací false. Nepřijímá
  žádné zprávy.
</p>

<h3 id="found-solution-condition">FoundSolutionCondition</h3>

<p>
  {javadoc "solver.condition.FoundSolutionCondition"} vrací true pokud bylo nalezeno alespoň jedno řešení (řešení je
  taková konfigurace, pro kterou {javadoc "problem.Problem#isSolution(cz.cvut.felk.cig.jcop.problem.Configuration)"}
  vrací true). Přijímá zprávu {javadoc "solver.message.MessageSolverStart"} na resetování svého stavu a
  {javadoc "solver.message.MessageSolutionFound"} jako notifikaci že bylo nalezeno řešení.
</p>

<h3 id="iteration-condition">IterationCondition</h3>

<p>
  {javadoc "solver.condition.IterationCondition"} počítá, kolik optimalizačních kroků proběhlo v&nbsp;iteraci solveru. Jakmile
  je dosaženo zadané hranice, vrací true. Přijímá zprávu {javadoc "solver.message.MessageOptimize"} na zvýšení
  interního čítače a {javadoc "solver.message.MessageSolverStart"} na jeho nastavení na nulu.
</p>

<h3 id="or-condition">OrCondition</h3>

<p>
  {javadoc "solver.condition.OrCondition"} se používá na vytváření komplexních podmínek. Může v&nbsp;sobě obsahovat
  libovolné množství dalších ukončovacích podmínek (dodané buď v&nbsp;konstruktoru nebo voláním {javadoc "solver.condition.OrCondition#addStopCondition(cz.cvut.felk.cig.jcop.solver.condition.StopCondition)"}).
  Kdykoli je podmínka vyhodnocena, vrací true, pokud alespoň jedna dílčí ukončovací podmínka vrací true. Nepřijímá
  žádné zprávy.
</p>

<h3 id="timeout-condition">TimeoutCondition</h3>

<p>
  {javadoc "solver.condition.TimeoutCondition"} omezuje jak dlouho může jedna iterace solveru běžet. Omezení se udává v&nbsp;milisekundách a&nbsp;je předáván v&nbsp;konstruktoru. Používá {javadoc "util.PreciseTime#getCpuTimeMili()"} na získání CPU time.
  Vrací true pokud již daný čas uplynul. Přijímá {javadoc "solver.message.MessageSolverStart"} pro restartování čítače
  času.
</p>