Tato kapitola pokrývá často kladené dotazy a obvyklé chyby, které dělají začínající uživatelé.
log4j:WARN No appenders could be found for logger (...)

Dostávám
log4j:WARN No appenders could be found for logger (...).
log4j:WARN Please initialize the log4j system properly.

chybu v konzoli
Řešení:

Potřebujete správně inicializovat Log4j. Toho lze dosáhnout tak, že přidáte log4j.properties do classpath (preferované řešení, navíc je zde soubor s výchozím nastavením přímo v JCOPu), použijete manuální konfiguraci jako: 1	org.apache.log4j.BasicConfigurator.configure();


nebo vypnete log4j úplně: 1	Logger.getRootLogger().setLevel(Level.OFF);