{block #title}Často Kladené Dotazy (FAQ){/block}
{block #chapter}1.3{/block}
{block #content}

<p>
  Tato kapitola pokrývá často kladené dotazy a obvyklé chyby, které dělají začínající uživatelé.
</p>

<h3>log4j:WARN No appenders could be found for logger (...)</h3>
<p>
  Dostávám
</p>
<pre>
log4j:WARN No appenders could be found for logger (...).
log4j:WARN Please initialize the log4j system properly.
</pre>
<p>
  chybu v konzoli
</p>
<h4>Řešení:</h4>
<p>
  Potřebujete správně inicializovat Log4j. Toho lze dosáhnout tak, že přidáte <code>log4j.properties</code> do
  classpath (preferované řešení, navíc je zde soubor s výchozím nastavením přímo v JCOPu), použijete manuální konfiguraci
  jako:
</p>
<pre class="brush: java;">org.apache.log4j.BasicConfigurator.configure();</pre>
<p>
  nebo vypnete log4j úplně:
</p>
<pre class="brush: java;">Logger.getRootLogger().setLevel(Level.OFF);</pre>