{block #title}Download{/block}
{block #chapter}1.2{/block}
{block #content}

<p>
  Latest stable:
</p>
<p>None</p>

<p>
  Latest beta (15.3.2010):
</p>
<ul>
  <li><a href="{$basePath}/media/latest/jcop.7z">7zip archive</a> (md5 checksum d5932a5d823ecf2795813e34e16b9077)</li>
  <li><a href="{$basePath}/media/latest/jcop.tgz">tgz archive</a> (md5 checksum ec38044aef0c0bbd9e0ff50581ed20b6)</li>
  <li><a href="{$basePath}/media/latest/jcop.zip">zip archive</a> (md5 checksum 702c8f8a3d5079aa15668b917b8f21e1)</li>
</ul>
