{block #title}Instalace{/block}
{block #chapter}2.2{/block}
{block #content}

<p>
  Nejprve je nutné stáhnout JCOP soubory. Nejnovější verze se nachází na stránce <a href="http://sourceforge.net/projects/jcop/files/">ke
  stažení</a>.
</p>
<p>
  Archiv obsahuje všechno, co potřebujete k&nbsp;běhu JCOPu - jak JAR soubor tak všechny knihovny, které JCOP používá (jako
  například <a href="http://logging.apache.org/log4j/">log4j</a> nebo <a href="http://www.jfree.org/jfreechart/">JFreeChart</a>).
  Obsah archivu je zobrazen na <a href="#fig1">obrázku 1</a>. Můžete ho rozbalit kam chcete, jenom ho budete muset přidat
  do knihoven v&nbsp;projektu.
</p>
<p>
  Obvykle je třeba pouze přidat soubor <code>jcop.jar</code> a&nbsp;všechny ostatní knihovny se přidají automaticky. Pokud ne,
  přidejte je manuálně, stejně jako jste přidali <code>jcop.jar</code>. Následují pokyny jak přidat JAR soubor do projektu
  pro běžně používaná IDE.
</p>

{include "../fig.phtml", "url" => "jcop-archive.png", "url_thumb" => "jcop-archive_resize.png", "title" => "obsah archivu JCOP", "fig" => "1"}

<h3>IntelliJ IDEA 9.0.1 Community Edition</h3>

<p>
  Vytvořte nový projekt pomocí File &rarr; New Project. Vyberte Create project from scratch a&nbsp;postupujte podle průvodce
  (nezapomeňte přidat alespoň jeden modul). Poté jděte do File &rarr; Project Structure a&nbsp;vyberte Libraries z&nbsp;Project
  settings. Klikněte na New Project Library (ikonka plusu nebo alt+insert) a&nbsp;vyplňte jcop jako název. Měli byste vidět
  něco jako je na <a href="#fig2">obrázku 2</a>.
</p>

{include "../fig.phtml", "url" => "idea-new-library.png", "url_thumb" => "idea-new-library_resize.png", "title" => "IntelliJ IDEA nová knihovna", "fig" => "2"}

<p>
  Poté, co jste přidali novou knihovny, klikněte na Attach Classes a&nbsp;přidejte soubor <code>jcop.jar</code>. Výsledek by
  měl vypadat jako na <a href="#fig3">obrázku 3</a>.
</p>

{include "../fig.phtml", "url" => "idea-attach-jar.png", "url_thumb" => "idea-attach-jar_resize.png", "title" => "IntelliJ IDEA přidaný JAR soubor", "fig" => "3"}

<p>
  JCOP by měl být připraven. Vyzkoušejte ho tak, že si  <a href="#test-app">uděláte testovací aplikaci</a>.
</p>


<h3>NetBeans IDE 6.8</h3>

<p>
  Vytvořte nový projekt Java Application pomocí File &rarr; New Project, kategorii zvolte jako je na <a href="#fig4">obrázku 4</a>.
</p>

{include "../fig.phtml", "url" => "netbeans-new-project.png", "url_thumb" => "netbeans-new-project_resize.png", "title" => "NetBeans IDE nový projekt", "fig" => "4"}

<p>
  Klikněte pravým tlačítkem na Libraries ve stromu projektu a&nbsp;vyberte Add JAR/Folder jako je na  <a href="#fig5">obrázku 5</a>
  a&nbsp;přidejte <code>jcop.jar</code>.
</p>

{include "../fig.phtml", "url" => "netbeans-add-jar.png", "url_thumb" => "netbeans-add-jar_resize.png", "title" => "NetBeans IDE Add JAR/Folder", "fig" => "5"}

<p>
  JCOP by měl být připraven. Vyzkoušejte ho tak, že si  <a href="#test-app">uděláte testovací aplikaci</a>.
</p>

<h3>Eclipse IDE for Java Developers	(1.2.1.20090918-0703)</h3>

<p>
  Vytvořte nový projekt pomocí File &rarr; New &rarr; Java project. Klikněte pravým tlačítkem na projekt a&nbsp;vyberte
  Properties jako je zobrazeno v <a href="#fig6">obrázku 6</a>.
</p>

{include "../fig.phtml", "url" => "eclipse-properties.png", "url_thumb" => "eclipse-properties_resize.png", "title" => "Eclipse Properties projektu", "fig" => "6"}

<p>
  Najeďte na Java Build Path a&nbsp;vyberte Libraries. Poté klikněte na Add External JARs a&nbsp;vyberte <code>jcop.jar</code> jako
  na <a href="#fig7">obrázku 7</a>.
</p>

{include "../fig.phtml", "url" => "eclipse-add-jars.png", "url_thumb" => "eclipse-add-jars_resize.png", "title" => "Eclipse Add External JARs", "fig" => "7"}

<p>
  JCOP by měl být připraven. Vyzkoušejte ho tak, že si  <a href="#test-app">uděláte testovací aplikaci</a>.
</p>

<h3 id="test-app">Testovací aplikace</h3>

<p>
  Abyste vyzkoušeli, že JCOP je správně nainstalován, použijte tuto jednoduchou aplikaci. Pouze přidejte do vašeho
  projektu novu Java Main Class s&nbsp;následujícím kódem a&nbsp;pusťte ji (název package se může lišit podle toho, v&nbsp;jaké package
  se nachází Main Class).
</p>

<pre class="brush: java;">
package jcoptest;

import cz.cvut.felk.cig.jcop.algorithm.graphsearch.bfs.BreadthFirstSearch;
import cz.cvut.felk.cig.jcop.problem.knapsack.Knapsack;
import cz.cvut.felk.cig.jcop.result.render.CSVRender;
import cz.cvut.felk.cig.jcop.result.render.JFreeChartRender;
import cz.cvut.felk.cig.jcop.result.render.SimpleRender;
import cz.cvut.felk.cig.jcop.result.render.XMLRender;
import cz.cvut.felk.cig.jcop.solver.SimpleSolver;
import cz.cvut.felk.cig.jcop.solver.Solver;
import java.io.File;
import java.io.IOException;

public class Main {
    public static void main(String[] args) throws IOException {
        Solver solver = new SimpleSolver(new BreadthFirstSearch(), new Knapsack("9000 4 100 18 114 42 136 88 192 3 223"));
        solver.addListener(new JFreeChartRender("Test"));
        solver.addRender(new SimpleRender());
        solver.addRender(new CSVRender(new File("test.csv")));
        solver.addRender(new XMLRender(new File("test.xml")));
        solver.run();
        solver.render();
    }
}
</pre>

<p>
  Pokud vše proběhlo bez problémů, měli byste vidět text podobný následujícímu v&nbsp;konzoli:
</p>

<pre class="brush: plain;">
0 [main] INFO cz.cvut.felk.cig.jcop.solver.SimpleSolver  - Started solver.
16 [main] INFO cz.cvut.felk.cig.jcop.solver.SimpleSolver  - Started optimize, BreadthFirstSearch [] on Knapsack [line=9000 4 100 18 114 42 136 88 192 3 223].
16 [main] WARN cz.cvut.felk.cig.jcop.solver.SimpleSolver  - Got exception CannotContinueException.
16 [main] INFO cz.cvut.felk.cig.jcop.solver.SimpleSolver  - Stopped optimize.
31 [main] INFO cz.cvut.felk.cig.jcop.solver.SimpleSolver  - Stopped solver.

=== Algorithm BreadthFirstSearch [] used on problem Knapsack [line=9000 4 100 18 114 42 136 88 192 3 223] ===
  CPU Time:                       1 [ms]
  System Time:                    1 [ms]
  User Time:                      1 [ms]
  Clock Time:                    15 [ms]
  Optimize counter:              16 [-]
  Optimize/sec (CPU):         16000 [1/s]
  Optimize/sec (Clock):        1066 [1/s]
  Best solution:         Configuration{!="{"}attributes=[1, 1, 0, 1], operationHistory={!="{"}0:Empty knapsack created, 1:AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=0, weight=18, price=114}}, 2:AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=1, weight=42, price=136}}, 3:AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=3, weight=3, price=223}}}}
  Depth:                          3 [-]
  Fitness:                    473,0 [-]
  Ended with exception:  cz.cvut.felk.cig.jcop.algorithm.CannotContinueException: No more items in queue
 </pre>

 <p>
  , graf podobný <a href="#fig8">obrázku 8</a> by se měl zobrazit a&nbsp;soubory <code>test.xml</code> a <code>test.csv</code>
  by měly být ve working directory (pracovní složce). Jejich obsah by měl být podobný tomu, co je zobrazeno níže.
 </p>

 {include "../fig.phtml", "url" => "test-app-graph.png", "url_thumb" => "test-app-graph_resize.png", "title" => "Graf testovací aplikace", "fig" => "8"}

<pre class="brush: xml;">
&lt;?xml version="1.0" standalone="yes"?&gt;
&lt;result&gt;
  &lt;experiment date='Tue Mar 16 10:26:59 CET 2010'&gt;&lt;/experiment&gt;
  &lt;entry exception='CannotContinueException' clock-time='15' system-time='1' user-time='16' algorithm='BreadthFirstSearch []' cpu-time='16' optimize-counter='16' problem='Knapsack [line=9000 4 100 18 114 42 136 88 192 3 223]'&gt;
    &lt;best-solution fitness='473.0'&gt;
      &lt;operations&gt;
        &lt;operation index='0' label='Empty knapsack created'&gt;&lt;/operation&gt;
        &lt;operation index='1' label='AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=0, weight=18, price=114}}'&gt;&lt;/operation&gt;
        &lt;operation index='2' label='AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=1, weight=42, price=136}}'&gt;&lt;/operation&gt;
        &lt;operation index='3' label='AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=3, weight=3, price=223}}'&gt;&lt;/operation&gt;
      &lt;/operations&gt;
      &lt;attributes&gt;
        &lt;attribute index='0' value='1' human-readable-value='1'&gt;&lt;/attribute&gt;
        &lt;attribute index='1' value='1' human-readable-value='1'&gt;&lt;/attribute&gt;
        &lt;attribute index='2' value='0' human-readable-value='0'&gt;&lt;/attribute&gt;
        &lt;attribute index='3' value='1' human-readable-value='1'&gt;&lt;/attribute&gt;
      &lt;/attributes&gt;
    &lt;/best-solution&gt;
  &lt;/entry&gt;
&lt;/result&gt;
</pre>

<pre class="brush: plain;">
Algorithm,Problem,CPU Time [ms],System Time [ms],User Time [ms],Clock Time [ms],Optimize counter,Optimize/sec (CPU) [1/s],Optimize/sec (Clock) [1/s],Exception,Best solution,Depth,Fitness,Operations
BreadthFirstSearch [],Knapsack [line=9000 4 100 18 114 42 136 88 192 3 223],16,1,16,15,16,1000,1066,class cz.cvut.felk.cig.jcop.algorithm.CannotContinueException,"[1, 1, 0, 1]",3,473.0,"Empty knapsack created, AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=0, weight=18, price=114}}, AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=1, weight=42, price=136}}, AddOperation{!="{"}knapsackItem=KnapsackItem{!="{"}index=3, weight=3, price=223}}"
</pre>