/*
 * Copyright © 2010 by Ondrej Skalicka. All Rights Reserved
 */

package cz.cvut.felk.cig.jcop.solver.message;

/**
 * Classes implementing MessageListener interface are able to accept messages.
 * <p/>
 * Messages are usually generated by Solvers, however this interface does not limit who can create new message.
 *
 * @author Ondrej Skalicka
 */
public interface MessageListener {
    /**
     * Passes a message to the listener.
     *
     * @param message the message passed to the listener
     */
    void onMessage(Message message);
}
